import { Department, FieldTeam, Issue, CivicChallenge, Hotspot } from './types';

export const mockDepartments: Department[] = [
  { id: 'dept-roads', name: 'Municipal Roads', activeIssues: 124, resolvedToday: 32, slaComplianceRate: 88 },
  { id: 'dept-water', name: 'Water & Sanitation', activeIssues: 87, resolvedToday: 18, slaComplianceRate: 92 },
  { id: 'dept-waste', name: 'Waste Management', activeIssues: 54, resolvedToday: 41, slaComplianceRate: 95 },
  { id: 'dept-electric', name: 'Electrical Works', activeIssues: 32, resolvedToday: 12, slaComplianceRate: 81 },
  { id: 'dept-traffic', name: 'Traffic Management', activeIssues: 45, resolvedToday: 21, slaComplianceRate: 85 },
];

export const mockFieldTeams: FieldTeam[] = [
  { id: 'team-r1', name: 'Road Team Alpha', departmentId: 'dept-roads', status: 'WORKING', currentIssueId: 'CP-1047', location: { lat: 30.7050, lng: 76.7460 }, members: 5 },
  { id: 'team-r2', name: 'Road Team Beta', departmentId: 'dept-roads', status: 'AVAILABLE', location: { lat: 30.7100, lng: 76.7500 }, members: 4 },
  { id: 'team-w1', name: 'Water Rapid Response', departmentId: 'dept-water', status: 'EN_ROUTE', currentIssueId: 'CP-1051', location: { lat: 30.7040, lng: 76.7430 }, members: 3 },
  { id: 'team-w2', name: 'Sanitation Team Beta', departmentId: 'dept-waste', status: 'AVAILABLE', location: { lat: 30.7200, lng: 76.7600 }, members: 6 },
  { id: 'team-e1', name: 'Grid Maintenance A', departmentId: 'dept-electric', status: 'WORKING', currentIssueId: 'CP-1039', location: { lat: 30.7080, lng: 76.7480 }, members: 2 },
];

export const mockHotspots: Hotspot[] = [
  {
    id: 'hs-1',
    name: 'Sector 45–47',
    description: 'High density of active reports detected in this sector.',
    location: { lat: 30.7046, lng: 76.7456, radius: 400 },
    reportCount: 14,
    topCategory: 'Waterlogging',
    riskLevel: 'HIGH',
    trend: 32
  },
  {
    id: 'hs-2',
    name: 'Sector 17 Plaza',
    description: 'Emerging cluster of civic issues in commercial zone.',
    location: { lat: 30.7400, lng: 76.7800, radius: 300 },
    reportCount: 5,
    topCategory: 'Garbage',
    riskLevel: 'MEDIUM',
    trend: 12
  }
];

export const mockIssues: Issue[] = [
  {
    id: 'CP-1047',
    title: 'Major pothole near University Road',
    description: 'A massive pothole has formed in the middle lane causing severe traffic slowdowns and risking vehicle damage.',
    category: 'Pothole',
    location: { lat: 30.7052, lng: 76.7465, address: 'Sector 47, University Road', ward: 'Ward 4', zone: 'South Zone' },
    photos: ['https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&q=80&w=800'],
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    priorityScore: 87,
    citizenUrgency: 'URGENT',
    estimatedResolutionTime: '6-24 hours',
    reporterId: 'user-1',
    assignedDepartmentId: 'dept-roads',
    assignedTeamId: 'team-r1',
    slaTarget: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    aiAnalysis: {
      confidence: 96,
      detectedCategory: 'Pothole',
      severity: 'HIGH',
      safetyRisk: 'MEDIUM',
      suggestedDepartment: 'Road Maintenance',
      priorityScore: 87,
      priorityReasoning: [{ factor: 'High traffic impact', score: 15 }, { factor: 'Vehicle damage risk', score: 10 }, { factor: 'Citizen flagged as URGENT', score: 20 }]
    },
    timeline: [
      { id: 'tl-1', status: 'REPORTED', timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(), description: 'Issue reported', actor: 'Citizen' },
      { id: 'tl-1a', status: 'AI_VERIFIED', timestamp: new Date(Date.now() - 11.5 * 60 * 60 * 1000).toISOString(), description: 'AI Analysis completed', actor: 'System' },
      { id: 'tl-1b', status: 'ASSIGNED', timestamp: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(), description: 'Routed to Road Maintenance', actor: 'System' },
      { id: 'tl-3', status: 'ASSIGNED', timestamp: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(), description: 'Assigned to Road Team Alpha', actor: 'Admin' },
      { id: 'tl-4', status: 'IN_PROGRESS', timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), description: 'Team working on repair', actor: 'Field Team' },
    ]
  },
  {
    id: 'CP-1051',
    title: 'Severe Waterlogging',
    description: 'Drains blocked, water level rising dangerously close to shops.',
    category: 'Waterlogging',
    location: { lat: 30.7030, lng: 76.7420, address: 'Sector 45 Market', ward: 'Ward 4', zone: 'South Zone' },
    photos: [],
    status: 'ASSIGNED',
    priority: 'CRITICAL',
    priorityScore: 95,
    citizenUrgency: 'HIGH',
    estimatedResolutionTime: '24-48 hours',
    reporterId: 'user-3',
    assignedDepartmentId: 'dept-water',
    assignedTeamId: 'team-w1',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    slaTarget: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    aiAnalysis: { confidence: 92, detectedCategory: 'Waterlogging', severity: 'CRITICAL', safetyRisk: 'HIGH', suggestedDepartment: 'Water & Sewerage', priorityScore: 95, priorityReasoning: [{ factor: 'Property damage risk', score: 15 }, { factor: 'Health hazard', score: 10 }] },
    timeline: [{ id: 't1', status: 'REPORTED', timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), description: 'Reported', actor: 'Citizen' }]
  },
  {
    id: 'CP-1039',
    title: 'Flickering Streetlight',
    description: 'Streetlight is flickering constantly, completely off most of the time.',
    category: 'Streetlight',
    location: { lat: 30.7085, lng: 76.7490, address: 'Sector 46 Residential Area', ward: 'Ward 4', zone: 'South Zone' },
    photos: [],
    status: 'IN_PROGRESS',
    priority: 'LOW',
    priorityScore: 35,
    citizenUrgency: 'LOW',
    estimatedResolutionTime: '5-10 days',
    reporterId: 'user-4',
    assignedDepartmentId: 'dept-electric',
    assignedTeamId: 'team-e1',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    slaTarget: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    aiAnalysis: { confidence: 88, detectedCategory: 'Streetlight', severity: 'LOW', safetyRisk: 'LOW', suggestedDepartment: 'Electrical Department', priorityScore: 35, priorityReasoning: [{ factor: 'Routine maintenance', score: 20 }] },
    timeline: [{ id: 't1', status: 'REPORTED', timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), description: 'Reported', actor: 'Citizen' }]
  },
  {
    id: 'CP-1062',
    title: 'Overflowing Garbage Bin',
    description: 'The garbage bin has not been cleared for days, causing a mess and foul smell.',
    category: 'Garbage',
    location: { lat: 30.7060, lng: 76.7480, address: 'Sector 47 Market', ward: 'Ward 4', zone: 'South Zone' },
    photos: [],
    status: 'REPORTED',
    priority: 'MEDIUM',
    priorityScore: 55,
    citizenUrgency: 'MODERATE',
    estimatedResolutionTime: '2-5 days',
    reporterId: 'user-1',
    assignedDepartmentId: 'dept-waste',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    slaTarget: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    aiAnalysis: { confidence: 90, detectedCategory: 'Garbage', severity: 'MEDIUM', safetyRisk: 'LOW', suggestedDepartment: 'Sanitation Department', priorityScore: 55, priorityReasoning: [{ factor: 'Public nuisance', score: 30 }] },
    timeline: [{ id: 't1', status: 'REPORTED', timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), description: 'Reported', actor: 'Citizen' }]
  },
  {
    id: 'CP-1060',
    title: 'Garbage Dump Overflow',
    description: 'Trash has not been collected for 4 days.',
    category: 'Garbage',
    location: { lat: 30.7410, lng: 76.7810, address: 'Sector 17 Commercial Area', ward: 'Ward 1', zone: 'Central Zone' },
    photos: [],
    status: 'REPORTED',
    priority: 'HIGH',
    priorityScore: 78,
    reporterId: 'user-5',
    slaTarget: new Date(Date.now() + 1 * 60 * 60 * 1000).toISOString(), // AT_RISK
    createdAt: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
    timeline: [{ id: 't1', status: 'REPORTED', timestamp: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(), description: 'Reported', actor: 'Citizen' }]
  },
  {
    id: 'CP-1061',
    title: 'Traffic Signal Broken',
    description: 'Signal at main intersection is completely dead.',
    category: 'Traffic Sign',
    location: { lat: 30.7380, lng: 76.7780, address: 'Sector 17/18 Crossing', ward: 'Ward 1', zone: 'Central Zone' },
    photos: [],
    status: 'REPORTED',
    priority: 'CRITICAL',
    priorityScore: 92,
    reporterId: 'user-6',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    timeline: [{ id: 't1', status: 'REPORTED', timestamp: new Date().toISOString(), description: 'Reported', actor: 'Citizen' }]
  },
  {
    id: 'CP-1020',
    title: 'Broken Footpath',
    description: 'Paving stones missing, dangerous for elderly.',
    category: 'Broken Footpath',
    location: { lat: 30.7060, lng: 76.7440, address: 'Sector 45 Park Edge', ward: 'Ward 4', zone: 'South Zone' },
    photos: [],
    status: 'RESOLVED',
    priority: 'LOW',
    priorityScore: 35,
    reporterId: 'user-7',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    timeline: [{ id: 't1', status: 'REPORTED', timestamp: new Date().toISOString(), description: 'Reported', actor: 'Citizen' }]
  },
  {
    id: 'CP-1021',
    title: 'Clogged Drain',
    description: 'Drain is fully blocked with plastic waste.',
    category: 'Waterlogging',
    location: { lat: 30.7040, lng: 76.7450, address: 'Sector 45 C', ward: 'Ward 4', zone: 'South Zone' },
    photos: [],
    status: 'REPORTED',
    priority: 'MEDIUM',
    priorityScore: 55,
    reporterId: 'user-8',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    timeline: [{ id: 't1', status: 'REPORTED', timestamp: new Date().toISOString(), description: 'Reported', actor: 'Citizen' }]
  },
  {
    id: 'CP-1022',
    title: 'Clogged Drain 2',
    description: 'Another drain blocked here.',
    category: 'Waterlogging',
    location: { lat: 30.7042, lng: 76.7452, address: 'Sector 45 C', ward: 'Ward 4', zone: 'South Zone' },
    photos: [],
    status: 'REPORTED',
    priority: 'MEDIUM',
    priorityScore: 52,
    reporterId: 'user-9',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    timeline: [{ id: 't1', status: 'REPORTED', timestamp: new Date().toISOString(), description: 'Reported', actor: 'Citizen' }]
  },
  {
    id: 'CP-1023',
    title: 'Water pipe leak',
    description: 'Fresh water leaking onto the street.',
    category: 'Waterlogging',
    location: { lat: 30.7038, lng: 76.7448, address: 'Sector 45 C', ward: 'Ward 4', zone: 'South Zone' },
    photos: [],
    status: 'REPORTED',
    priority: 'HIGH',
    priorityScore: 81,
    reporterId: 'user-10',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    timeline: [{ id: 't1', status: 'REPORTED', timestamp: new Date().toISOString(), description: 'Reported', actor: 'Citizen' }]
  },
  {
    id: 'CP-1024',
    title: 'Pothole cluster',
    description: 'Multiple potholes causing traffic issues.',
    category: 'Pothole',
    location: { lat: 30.7055, lng: 76.7470, address: 'Sector 47', ward: 'Ward 4', zone: 'South Zone' },
    photos: [],
    status: 'REPORTED',
    priority: 'HIGH',
    priorityScore: 84,
    reporterId: 'user-11',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    timeline: [{ id: 't1', status: 'REPORTED', timestamp: new Date().toISOString(), description: 'Reported', actor: 'Citizen' }]
  },
  {
    id: 'CP-1025',
    title: 'Streetlight out',
    description: 'Corner streetlight broken.',
    category: 'Streetlight',
    location: { lat: 30.7080, lng: 76.7485, address: 'Sector 46', ward: 'Ward 4', zone: 'South Zone' },
    photos: [],
    status: 'REPORTED',
    priority: 'LOW',
    priorityScore: 25,
    reporterId: 'user-12',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    timeline: [{ id: 't1', status: 'REPORTED', timestamp: new Date().toISOString(), description: 'Reported', actor: 'Citizen' }]
  },
  {
    id: 'CP-1026',
    title: 'Stray animals',
    description: 'Stray dogs aggressive in the park.',
    category: 'Public Safety',
    location: { lat: 30.7070, lng: 76.7430, address: 'Sector 45 Park', ward: 'Ward 4', zone: 'South Zone' },
    photos: [],
    status: 'REPORTED',
    priority: 'MEDIUM',
    priorityScore: 60,
    reporterId: 'user-13',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    timeline: [{ id: 't1', status: 'REPORTED', timestamp: new Date().toISOString(), description: 'Reported', actor: 'Citizen' }]
  },
  {
    id: 'CP-1027',
    title: 'Garbage not collected',
    description: 'Overflowing bins.',
    category: 'Garbage',
    location: { lat: 30.7050, lng: 76.7445, address: 'Sector 45', ward: 'Ward 4', zone: 'South Zone' },
    photos: [],
    status: 'REPORTED',
    priority: 'MEDIUM',
    priorityScore: 45,
    reporterId: 'user-14',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    timeline: [{ id: 't1', status: 'REPORTED', timestamp: new Date().toISOString(), description: 'Reported', actor: 'Citizen' }]
  },
  {
    id: 'CP-1028',
    title: 'Garbage dump',
    description: 'Illegal dumping ground forming.',
    category: 'Garbage',
    location: { lat: 30.7052, lng: 76.7448, address: 'Sector 45', ward: 'Ward 4', zone: 'South Zone' },
    photos: [],
    status: 'REPORTED',
    priority: 'MEDIUM',
    priorityScore: 48,
    reporterId: 'user-15',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    timeline: [{ id: 't1', status: 'REPORTED', timestamp: new Date().toISOString(), description: 'Reported', actor: 'Citizen' }]
  },
  {
    id: 'CP-1029',
    title: 'Broken road',
    description: 'Road surface completely worn off.',
    category: 'Other',
    location: { lat: 30.7065, lng: 76.7480, address: 'Sector 47', ward: 'Ward 4', zone: 'South Zone' },
    photos: [],
    status: 'REPORTED',
    priority: 'HIGH',
    priorityScore: 75,
    reporterId: 'user-16',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    timeline: [{ id: 't1', status: 'REPORTED', timestamp: new Date().toISOString(), description: 'Reported', actor: 'Citizen' }]
  },
  {
    id: 'CP-1030',
    title: 'Open manhole',
    description: 'Extremely dangerous open manhole.',
    category: 'Public Safety',
    location: { lat: 30.7045, lng: 76.7460, address: 'Sector 45/47 Divider', ward: 'Ward 4', zone: 'South Zone' },
    photos: [],
    status: 'REPORTED',
    priority: 'CRITICAL',
    priorityScore: 98,
    reporterId: 'user-17',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    timeline: [{ id: 't1', status: 'REPORTED', timestamp: new Date().toISOString(), description: 'Reported', actor: 'Citizen' }]
  },
  {
    id: 'CP-1031',
    title: 'Street signs missing',
    description: 'Sector direction boards broken.',
    category: 'Traffic Sign',
    location: { lat: 30.7090, lng: 76.7495, address: 'Sector 46', ward: 'Ward 4', zone: 'South Zone' },
    photos: [],
    status: 'REPORTED',
    priority: 'LOW',
    priorityScore: 20,
    reporterId: 'user-18',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    timeline: [{ id: 't1', status: 'REPORTED', timestamp: new Date().toISOString(), description: 'Reported', actor: 'Citizen' }]
  },
  {
    id: 'CP-1032',
    title: 'Waterlogging again',
    description: 'Slight rain causes flooding.',
    category: 'Waterlogging',
    location: { lat: 30.7035, lng: 76.7435, address: 'Sector 45 Market', ward: 'Ward 4', zone: 'South Zone' },
    photos: [],
    status: 'REPORTED',
    priority: 'HIGH',
    priorityScore: 82,
    reporterId: 'user-19',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    timeline: [{ id: 't1', status: 'REPORTED', timestamp: new Date().toISOString(), description: 'Reported', actor: 'Citizen' }]
  },
  {
    id: 'CP-1033',
    title: 'Dead animal',
    description: 'Requires immediate sanitation clearance.',
    category: 'Garbage',
    location: { lat: 30.7420, lng: 76.7820, address: 'Sector 17', ward: 'Ward 1', zone: 'Central Zone' },
    photos: [],
    status: 'REPORTED',
    priority: 'MEDIUM',
    priorityScore: 50,
    reporterId: 'user-20',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    timeline: [{ id: 't1', status: 'REPORTED', timestamp: new Date().toISOString(), description: 'Reported', actor: 'Citizen' }]
  },
  {
    id: 'CP-1034',
    title: 'Fallen Tree',
    description: 'Blocking the entire road.',
    category: 'Public Safety',
    location: { lat: 30.7430, lng: 76.7830, address: 'Sector 17', ward: 'Ward 1', zone: 'Central Zone' },
    photos: [],
    status: 'REPORTED',
    priority: 'CRITICAL',
    priorityScore: 96,
    reporterId: 'user-21',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    timeline: [{ id: 't1', status: 'REPORTED', timestamp: new Date().toISOString(), description: 'Reported', actor: 'Citizen' }]
  },
  {
    id: 'CP-1035',
    title: 'Pothole',
    description: 'Small pothole near sector entry.',
    category: 'Pothole',
    location: { lat: 30.7380, lng: 76.7750, address: 'Sector 16', ward: 'Ward 1', zone: 'Central Zone' },
    photos: [],
    status: 'REPORTED',
    priority: 'LOW',
    priorityScore: 30,
    reporterId: 'user-22',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    timeline: [{ id: 't1', status: 'REPORTED', timestamp: new Date().toISOString(), description: 'Reported', actor: 'Citizen' }]
  },
  {
    id: 'CP-1036',
    title: 'Sewer Overflow',
    description: 'Sewer water overflowing onto the main road.',
    category: 'Waterlogging',
    location: { lat: 30.7025, lng: 76.7410, address: 'Sector 45 Border', ward: 'Ward 4', zone: 'South Zone' },
    photos: [],
    status: 'REPORTED',
    priority: 'CRITICAL',
    priorityScore: 91,
    reporterId: 'user-23',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    timeline: [{ id: 't1', status: 'REPORTED', timestamp: new Date().toISOString(), description: 'Reported', actor: 'Citizen' }]
  }
];

export const mockChallenges: CivicChallenge[] = [
  {
    id: 'CH-001',
    title: 'Recurring Urban Waterlogging',
    description: 'Chandigarh Sector 45 experiences severe waterlogging during every monsoon.',
    location: 'Sector 45',
    severity: 'CRITICAL',
    rewardPoints: 5000,
    status: 'OPEN',
    proposalsCount: 12
  }
];

export const mockRecentActivity = [
  { id: 'act-1', time: '2 min ago', text: 'Road Team Alpha assigned to CP-1047' },
  { id: 'act-2', time: '8 min ago', text: 'New high-priority pothole detected' },
  { id: 'act-3', time: '17 min ago', text: 'CP-1020 marked resolved' },
  { id: 'act-4', time: '32 min ago', text: '4 reports clustered into Sector 45 hotspot' },
];
